### PR TITLE
Support reading from IO

### PR DESCRIPTION
**Pull request by taf2**
Add support for reading wave file data from an IO interface instead of a filename only

### CODE REVIEW

**Comment by anmishra** [comment]
@taf2 Hope you are doing great.The question I am going to ask is completely irrelevant. I just wanted to draw your attention. I am using curb gem v0.9.1 as part of my current project. And while connecting to TLSv1.2 enforced server I am getting SSLConnect error from my app. But it works when I execute the same code from within irb, and doesn't work from within bundle exec irb. I need your input here very badly.

**Comment by donv** [comment]
I am looking for this feature as well to enable converting values in a database without temporarily storing the content in files.

**Comment by taf2** [comment]
@anmishra strange - want to send me an email to todd dot fisher at gmail dot com?   Perhaps we can figure it out.

@donv - yeah that is what the patches allow you to do - streaming wave file changes without touching the disk.

**Comment by donv** [comment]
@taf2 Do you have an example displaying the use with a DB?  What IO should I use?  StringIO is missing sysseek.

**Comment by jstrait** [comment]
@taf2 thanks for opening this! Support for this feature is now on the v0.8.0 branch, and will be included in that release. It should go out soon. However, I built an alternate implementation (with the same interface). Because of that, I won't merge this specific PR in, and will close it out. See the issue https://github.com/jstrait/wavefile/issues/21 for more info.

**Pull request closed without merging**
